### PR TITLE
Prevent NPE in tryCreateParentDirectories

### LINKED ISSUE #39: Unavoidable NPE for certain paths in YamlConfigurationStore
**Describe the bug**
Passing a path with no parent to `YamlConfigurationStore#update` or `YamlConfigurationStore#save` results in an unavoidable NPE.

A `Path` object where `parent == null` often occurs when creating a path that points to a file in the current working directory.

**To Reproduce**
```
Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
	at java.base/java.nio.file.Files.provider(Files.java:105)
	at java.base/java.nio.file.Files.exists(Files.java:2515)
	at de.exlll.configlib.YamlConfigurationStore.tryCreateParentDirectories(YamlConfigurationStore.java:94)
	at de.exlll.configlib.YamlConfigurationStoreTest.tryCreateParentDirectoriesReturnsIfParentIsNull(YamlConfigurationStoreTest.java:574)
```
```java
Config someConfig = ...;
YamlConfigurationStore<Config> store = ...;

Path path = Paths.get("config.yml");
store.save(someConfig, path);
```

**Expected behavior**
`YamlConfigurationStore#tryCreateParentDirectories` should gracefully return without doing anything.

**Additional context**
This issue cannot be avoided by setting `createParentDirectories` to false in the properties as the `Files.exists` check is executed earlier than that check.

### PR DESCRIPTION
**Pull request by tomwmth**
Fixes #39.

Additionally adds a test for the failure (tryCreateParentDirectories was made package-private for this purpose).

### CODE REVIEW

File: configlib-yaml/src/test/java/de/exlll/configlib/YamlConfigurationStoreTest.java [hunk 1]
```diff
@@ -557,4 +558,20 @@ void updateResolvesEnvVarsIfFileDoesOrDoesNotExist(boolean createFile) {
...
+    void tryCreateParentDirectoriesDoesNotThrowIfParentIsNull(boolean createParentDirectories) {
+        YamlConfigurationProperties properties = YamlConfigurationProperties.newBuilder()
+                .createParentDirectories(createParentDirectories)
+                .build();
+        YamlConfigurationStore<A> store = new YamlConfigurationStore<>(
+                A.class,
+                properties
+        );
+
+        Path path = Paths.get("config.yml");
```
Comment (Exlll) [inline configlib-yaml/src/test/java/de/exlll/configlib/YamlConfigurationStoreTest.java:573]: Should be `fs.getPath("config.yml")`

File: configlib-yaml/src/test/java/de/exlll/configlib/YamlConfigurationStoreTest.java [hunk 2]
```diff
@@ -557,4 +558,20 @@ void updateResolvesEnvVarsIfFileDoesOrDoesNotExist(boolean createFile) {
...
+        store.tryCreateParentDirectories(path);
```
Comment (Exlll) [inline configlib-yaml/src/test/java/de/exlll/configlib/YamlConfigurationStoreTest.java:574]: I don't think this line is necessary considering the `assertDoesNotThrow` call below.

**Review by Exlll — CHANGES_REQUESTED** [review]

File: configlib-yaml/src/test/java/de/exlll/configlib/YamlConfigurationStoreTest.java (hunk 2 above)
Comment (tomwmth) [reply configlib-yaml/src/test/java/de/exlll/configlib/YamlConfigurationStoreTest.java:574]: Yep this was an accident, will fix

File: configlib-yaml/src/test/java/de/exlll/configlib/YamlConfigurationStoreTest.java (hunk 1 above)
Comment (tomwmth) [reply configlib-yaml/src/test/java/de/exlll/configlib/YamlConfigurationStoreTest.java:573]: Should have taken more time to look at the architecture of the other tests, will fix

**Review by Exlll — APPROVED** [review]
